media:
  - name: images
    label: "Images"
    input: apps/ars.guide/assets/media/images
    output: /media/images
content:
  - name: spellcrafting
    label: Pages
    type: collection
    path: apps/source-librarian/src/content/spellcrafting
    fields:
      - name: name
        type: string
      - name: slug
        type: string
      - name: description
        type: rich-text
        options:
          format: markdown
          media: false
      - name: links
        type: object
        list: true
        fields:
          - name: url
            type: string
          - name: text
            type: string
