backend:
  name: github
  repo: Ars-Nouveau/Ars-Auxilia
  branch: main
  open_authoring: true
  commit_messages:
    create: "feat(content/{{collection}}): {{path}}"
    update: "feat(content/{{collection}}): {{path}}"
    delete: "feat(content/{{collection}}): {{path}}"
    uploadMedia: "feat(content/{{collection}}): {{path}}"
    deleteMedia: "feat(content/{{collection}}): {{path}}"
    openAuthoring: "{{message}}"
media_folder: "apps/ars.guide/assets/media"
publish_mode: editorial_workflow
display_url: https://Ars.Guide
show_preview_links: false
search: false
collections:
  - name: spellcrafting
    label: Spellcrafting
    folder: 'apps/source-librarian/src/content/spellcrafting'
    create: true
    format: json
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Links"
        name: "links"
        widget: "list"
        label_singular: "link"
        min: 1
        max: 5
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Text", name: "text", widget: "string", required: false }
